/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: shig0 (https://sketchfab.com/shig0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-pc-case-5faa051ff3c944d29cde39d11c1c1e5e
Title: Gaming pc case
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 2.475]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="fan4_45" position={[0.178, 0.39, -0.035]} rotation={[0, 0, -Math.PI / 2]} scale={[0.009, 0.006, 0.009]}>
                <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.material} />
              </group>
              <group name="fan2_46" position={[-0.201, 0.28, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.009, 0.006, 0.009]}>
                <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.material} />
              </group>
              <group name="fan3_47" position={[-0.201, 0.16, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.009, 0.006, 0.009]}>
                <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.material} />
              </group>
              <group name="fan_48" position={[-0.201, 0.4, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.009, 0.006, 0.009]}>
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.material} />
              </group>
              <group name="arkakapak_0" position={[0.002, 0.252, 0.108]} scale={[0.191, 0.233, 0.001]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.n_panel_mesh} />
              </group>
              <group name="govde_1" scale={[1.115, 1.368, 0.629]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.n_panel_mesh} />
              </group>
              <group name="meshpanel001_2" position={[-0.205, 0.253, 0]} scale={[0.989, 15.485, 7.133]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.n_panel_mesh} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.n_panel_mesh} />
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.n_panel_mesh} />
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.MSI_LOGO} />
              </group>
              <group name="anakart_4" position={[0.065, 0.31, 0.08]} scale={[8.133, 10.167, 0.1]}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.anakart} />
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['anakart.rear']} />
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material} />
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material} />
              </group>
              <group name="b450_5" position={[-0.009, 0.218, 0.079]} scale={[0.714, 0.857, 0.143]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.anakart} />
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['anakart.rear']} />
              </group>
              <group name="cpu_power_6" position={[0.138, 0.457, 0.074]} scale={[0.26, 0.15, 0.143]}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.mat_siyah} />
              </group>
              <group name="atx_power_7" position={[-0.049, 0.351, 0.074]} scale={[0.152, 0.757, 0.152]}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.mat_siyah} />
              </group>
              <group name="sata1_8" position={[-0.049, 0.259, 0.074]} scale={[0.232, 0.253, 0.143]}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.mat_siyah} />
              </group>
              <group name="sata2_9" position={[-0.049, 0.239, 0.074]} scale={[0.232, 0.253, 0.143]}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.mat_siyah} />
              </group>
              <group name="bios_pil_yuvas��_10" position={[0.068, 0.195, 0.073]} rotation={[Math.PI / 2, 0, 0]} scale={0.59}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.mat_siyah} />
              </group>
              <group name="bios_pil_11" position={[0.067, 0.195, 0.074]} rotation={[Math.PI / 2, 0, 0]} scale={0.503}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.msi_logo} />
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ram_slot_12" position={[0.002, 0.38, 0.074]} scale={[0.012, 0.21, 0.015]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ram_slot001_13" position={[-0.007, 0.38, 0.074]} scale={[0.012, 0.21, 0.015]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ram_slot002_14" position={[-0.016, 0.38, 0.074]} scale={[0.012, 0.21, 0.015]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ram_slot003_15" position={[-0.025, 0.38, 0.074]} scale={[0.012, 0.21, 0.015]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.mat_siyah} />
              </group>
              <group name="mosfet_16" position={[0.145, 0.399, 0.073]} scale={[1, 1, 3.098]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.anakart} />
                <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials['anakart.rear']} />
              </group>
              <group name="mosfet001_17" position={[0.074, 0.459, 0.064]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1.37, 1]}>
                <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.anakart} />
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ses_18" position={[0.177, 0.234, 0.075]} rotation={[1.561, 0.323, 0.004]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.metal} />
                <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials['Material.005']} />
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ses001_19" position={[0.165, 0.234, 0.075]} rotation={[1.583, 0.119, -0.008]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.metal} />
                <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials['Material.005']} />
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ses002_20" position={[0.165, 0.226, 0.075]} rotation={[1.583, -0.062, -0.006]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.metal} />
                <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials['Material.005']} />
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.mat_siyah} />
              </group>
              <group name="ses003_21" position={[0.176, 0.227, 0.075]} rotation={[1.583, 0.116, -0.008]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.metal} />
                <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials['Material.005']} />
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.mat_siyah} />
              </group>
              <group name="pcie_x16_22" position={[0.097, 0.28, 0.078]} scale={[0.05, 0.05, 0.075]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.mat_siyah} />
                <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.metal} />
              </group>
              <group name="pcie_x16001_23" position={[0.097, 0.219, 0.078]} scale={[0.05, 0.05, 0.075]}>
                <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.mat_siyah} />
              </group>
              <group name="pcie_x1_24" position={[0.097, 0.261, 0.078]} scale={[0.05, 0.05, 0.075]}>
                <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.mat_siyah} />
              </group>
              <group name="pcie_x1001_25" position={[0.097, 0.241, 0.078]} scale={[0.05, 0.05, 0.075]}>
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.mat_siyah} />
              </group>
              <group name="pcie_x1002_26" position={[0.097, 0.2, 0.078]} scale={[0.05, 0.05, 0.075]}>
                <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.mat_siyah} />
              </group>
              <group name="sata1001_27" position={[-0.039, 0.161, 0.071]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.214, 0.253, 0.143]}>
                <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.mat_siyah} />
              </group>
              <group name="sata1002_28" position={[-0.021, 0.161, 0.071]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.232, 0.253, 0.143]}>
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.mat_siyah} />
              </group>
              <group name="dvi_29" position={[0.196, 0.406, 0.073]} scale={[0.089, 0.089, 0.022]}>
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.metal} />
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.mat_siyah} />
              </group>
              <group name="io_shield_30" position={[0.189, 0.395, 0.063]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.017, 0.057, 0.057]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.metal} />
              </group>
              <group name="ses004_31" position={[0.177, 0.324, 0.064]} scale={[0.044, 0.054, 0.06]}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.metal} />
                <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.mat_siyah} />
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Material.005']} />
                <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.material_10} />
              </group>
              <group name="usb_32" position={[0.162, 0.441, 0.069]} scale={0.044}>
                <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.metal} />
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.material_10} />
                <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.mat_siyah} />
              </group>
              <group name="usb001_33" position={[0.162, 0.374, 0.074]} scale={0.044}>
                <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.metal} />
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material_10} />
                <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.mat_siyah} />
              </group>
              <group name="usb002_34" position={[0.162, 0.349, 0.074]} scale={0.044}>
                <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.metal} />
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material_10} />
                <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.mat_siyah} />
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.green} />
                <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.yellow} />
              </group>
              <group name="socket_35" position={[0.055, 0.379, 0.077]} scale={[0.079, 0.065, 0.004]}>
                <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.mat_siyah} />
              </group>
              <group name="socketm_36" position={[0.038, 0.356, 0.077]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.MSI_LOGO} />
              </group>
              <group name="ram0_37" position={[-0.007, 0.376, 0.049]} rotation={[0, 0, Math.PI / 2]} scale={0.028}>
                <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.material} />
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material_13} />
                <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.mat_siyah} />
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.rametal} />
              </group>
              <group name="ram1_38" position={[-0.025, 0.376, 0.049]} rotation={[0, 0, Math.PI / 2]} scale={0.028}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material} />
                <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.material_13} />
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.mat_siyah} />
                <mesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.rametal} />
              </group>
              <group name="cpu_39" position={[0.06, 0.379, 0.075]} scale={[0.93, 0.93, 0.047]}>
                <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials['Material.002']} />
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials['Material.007']} />
                <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials['Material.003']} />
              </group>
              <group name="gpu_40" position={[0.072, 0.283, 0.01]} scale={[0.058, 0, 0.058]}>
                <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.gpu_b_plate} />
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.mat_siyah} />
                <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.gpu_pcb_f} />
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.gpu_pcb_r} />
                <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials['Material.005']} />
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.metal} />
                <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials['Material.006']} />
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.Material} />
                <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.gpu_fan_block} />
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.material} />
                <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials['Material.008']} />
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials['Material.009']} />
                <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.fan_frame} />
              </group>
              <group name="frame4_41" position={[0.178, 0.39, -0.035]} scale={[0.667, 4, 4]}>
                <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.fan_frame} />
              </group>
              <group name="frame2_42" position={[-0.201, 0.28, 0]} scale={[0.667, 4, 4]}>
                <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.fan_frame} />
              </group>
              <group name="frame3_43" position={[-0.201, 0.16, 0]} scale={[0.667, 4, 4]}>
                <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.fan_frame} />
              </group>
              <group name="frame1_44" position={[-0.201, 0.4, 0]} scale={[0.667, 4, 4]}>
                <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.fan_frame} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
